# Generated by Django 3.1.3 on 2020-12-01 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whats_free_on_craigslist_app', '0002_auto_20201201_0305'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listings',
            new_name='Listing',
        ),
    ]
