# Generated by Django 3.1.3 on 2020-12-01 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whats_free_on_craigslist_app', '0004_auto_20201201_0343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='listing_image_url',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='listing_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='listing_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='listing_url',
            new_name='url',
        ),
    ]
