# Generated by Django 3.1.3 on 2020-12-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whats_free_on_craigslist_app', '0005_auto_20201201_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='hood',
            field=models.TextField(default='', max_length=50),
        ),
    ]
