# Generated by Django 3.1.3 on 2020-12-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whats_free_on_craigslist_app', '0007_remove_listing_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='created',
            new_name='date',
        ),
        migrations.AddField(
            model_name='search',
            name='location',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='search',
            name='result_index',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='search',
            name='search',
            field=models.CharField(default='', max_length=500),
        ),
    ]
