# Generated by Django 3.1.3 on 2020-12-02 22:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('whats_free_on_craigslist_app', '0008_auto_20201202_2220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'ordering': ('creation_date',), 'verbose_name_plural': 'Searches'},
        ),
        migrations.RemoveField(
            model_name='search',
            name='date',
        ),
        migrations.AddField(
            model_name='search',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
    ]
