# Generated by Django 3.1.3 on 2020-12-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whats_free_on_craigslist_app', '0009_auto_20201202_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
