# Generated by Django 3.1.3 on 2020-12-03 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whats_free_on_craigslist_app', '0010_auto_20201202_2258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='search',
            options={'ordering': ['creation_date'], 'verbose_name_plural': 'Searches'},
        ),
    ]
